# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 CachyOS Hyprland Configuration              ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/decorations.conf
source = ~/.config/hypr/config/environment.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/monitor.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/windowrules.conf

# Modifying these configs can be done by creating a user defined config in the home directory, e.g.
## ~/.config/hypr/config/user-config.conf
# source = ~/.config/hypr/config/user-config.conf
general {
   col.active_border = rgba(542910ff) 
   col.inactive_border = rgba(44444488)
   border_size = 4
}
animation = workspaces, 1, 2, default
input {
    touchpad {
        natural_scroll = true
        scroll_factor = 0.8
    }
    sensitivity = 0.3
}

exec-once = udiskie --tray &

workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:eDP-1

exec-once = mako
exec-once = kdeconnectd
exec-once = ydotool
device {
    name = ydotoold-virtual-device
    kb_layout = us      # match your actual layout
    kb_variant =
    kb_options =
}
device {
  name = magic-mouse-2
  sensitivity = -1
  accel_profile = adaptive
}
cursor {
    no_hardware_cursors = true
}

windowrule = float on, match:class ^(steam_app_)
windowrule = fullscreen on, match:class ^(steam_app_)
windowrule = immediate on, match:class ^(steam_app_)
windowrule = idle_inhibit always, match:class ^(steam_app_)
windowrule = no_initial_focus on, match:class ^(steam_app_)
exec-once = /usr/lib/xdg-desktop-portal-kde
