$terminal     = kitty
$filemanager  = dolphin
$browser      = firefox
$editor       = vscodium
$applauncher  = wofi

$shot-region  = grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png
$shot-window  = grim -g "$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png
$shot-screen  = grim ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png
$locker       = hyprlock
$idlehandler  = swayidle -w timeout 300 '$locker' before-sleep '$locker'
